Udemy_ASPDotNET_MVC_Course/Controllers/Api/MovieController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Data.Entity;
using System.Web.Http;
using AutoMapper;
using Udemy_ASPDotNET_MVC_Course.Dtos;
using Udemy_ASPDotNET_MVC_Course.Models;

namespace Udemy_ASPDotNET_MVC_Course.Controllers.Api
{
	public class MovieController : ApiController
	{
		private ApplicationDbContext _context;

		public MovieController ()
		{
			_context = new ApplicationDbContext ();
		}
		// GET /api/movie
		public IHttpActionResult GetMovies (string query = null)
		{
			var moviesQuery = _context.Movies.Include (m => m.Genre).Where (m => m.NumberAvailable > 0);

			if (!string.IsNullOrWhiteSpace (query))
			{
				moviesQuery = moviesQuery.Where (m => m.Name.Contains (query));
			}	
				
			var movieDtos = moviesQuery	
				.ToList ()
				.Select (Mapper.Map<Movie, MovieDto>);
			return Ok (movieDtos);
		}

		// GET /api/movie/1
		public IHttpActionResult GetMovie (int id)
		{
			var movie = _context.Movies.SingleOrDefault (c => c.Id == id);

			if (movie == null)
			{
				return NotFound ();
			}
			return Ok (Mapper.Map<Movie, MovieDto> (movie));
		}

		// POST /api/movies
		[HttpPost]
		[System.Web.Mvc.Authorize (Roles = RoleName.CanManageMovies)]
		public IHttpActionResult CreateMovie (MovieDto movieDto)
		{
			if (!ModelState.IsValid)
			{
				return BadRequest ();
			}

			var movie = Mapper.Map<MovieDto, Movie> (movieDto);
			_context.Movies.Add (movie);
			_context.SaveChanges ();

			movieDto.Id = movie.Id;

			return Created (new Uri (Request.RequestUri + "/" + movie.Id), movieDto);
		}

		// PUT /api/movie/1
		[HttpPut]
		[System.Web.Mvc.Authorize (Roles = RoleName.CanManageMovies)]
		public IHttpActionResult UpdateMovie (int id, MovieDto movieDto)
		{
			if (!ModelState.IsValid)
			{
				return BadRequest ();
			}

			var movieInDb = _context.Movies.SingleOrDefault (c => c.Id == id);

			if (movieInDb == null)
			{
				return NotFound ();
			}

			Mapper.Map (movieDto, movieInDb);

			_context.SaveChanges ();
			return Ok ();
		}

		// DELETE /api/movie/1
		[HttpDelete]
		[System.Web.Mvc.Authorize (Roles = RoleName.CanManageMovies)]
		public IHttpActionResult DeleteMovie (int id)
		{
			var movieInDb = _context.Movies.SingleOrDefault (c => c.Id == id);

			if (movieInDb == null)
			{
				return NotFound ();
			}

			_context.Movies.Remove (movieInDb);
			_context.SaveChanges ();
			return Ok();
		}

	}
}

Udemy_ASPDotNET_MVC_Course/Controllers/RentalController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Udemy_ASPDotNET_MVC_Course.Controllers
{
    public class RentalController : Controller
    {
        // GET: Rental
        public ActionResult New()
        {
            return View();
        }
    }
}

Udemy_ASPDotNET_MVC_Course/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>@ViewBag.Title - My ASP.NET Application</title>
	@Styles.Render("~/Content/css")
	@Scripts.Render("~/bundles/modernizr")

</head>
<body>
	@Html.Partial("_NavBar")
	<div class="container body-content">
		@RenderBody()
		<hr/>
		<footer>
			<p>&copy; @DateTime.Now.Year - Rentalot</p>
		</footer>
	</div>

	@Scripts.Render("~/bundles/lib")
	@RenderSection("scripts", required: false)
</body>
</html>

Udemy_ASPDotNET_MVC_Course/Views/Shared/_NavBar.cshtml
<div class="navbar navbar-inverse navbar-fixed-top">
	<div class="container">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			@Html.ActionLink("Rentalot", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
		</div>
		<div class="navbar-collapse collapse">
			<ul class="nav navbar-nav">
				<li>@Html.ActionLink("Movies", "Index", "Movie")</li>
				<li>@Html.ActionLink("Customers", "Index", "Customer")</li>
				<li>@Html.ActionLink("New Rental", "New", "Rental")</li>
			</ul>
			@Html.Partial("_LoginPartial")
		</div>
	</div>
</div>